### ISSUE TITLE
feature request: opentopomap.org like theme

### ISSUE THREAD

**Issue by C-Makridis** [erik/derive#11]
Hello there,

I have no idea how easy or not it may be to implement it, but I think a theme based on opentopomap (repository: https://github.com/der-stefan/OpenTopoMap, result: www.opentopomap.org) would be nice.

Thank you for your time

**Comment by erik** [comment]
Turns out the tile library I'm using already supports OpenTopoMap, so this is a one line change.

It's included now 🙂
