### ISSUE TITLE
Not getting the exepcted outcome.

### ISSUE THREAD

**Issue by Nick-Z0** [erik/derive#23]
After dragging and dropping a .fit file, a pop-up comes up to save the .fit file. If I click save, it get saved on the desktop. 
What window should I be dropping it? In the github project window? 
Am I doing something wrong?

Maybe it is not working because I'm on mac?
Using chrome browser.

**Comment by erik** [comment]
Interesting, sounds like the code to register the drag and drop event listener isn't firing for some reason. Possibly an overzealous ad / JavaScript blocker  is preventing something from loading?

Would you be able to check if there are any errors in the devtools JavaScript console? And see if the same issue comes up when you try in an incognito window?

**Comment by Nick-Z0** [comment]
It turns out it works just fine. I just missed the link on top of the page. I was scrolling right past it to the bottom, where the readme is displayed. 
You could put the link also in the readme below because it is easy to miss, to avoid further confusion.
Great work by the way!

**Comment by erik** [comment]
Ahh got it. Thanks, that’s good feedback, I’ll add a more visible link.
