### ISSUE TITLE
Support FIT files with developer fields

### ISSUE THREAD

**Issue by laufhannes** [erik/derive#39]
Here's an example fit file that fails to display properly: [56683738298.zip](https://github.com/erik/derive/files/4739488/56683738298.zip)  
![image](https://user-images.githubusercontent.com/8313118/83938546-9ea97600-a7d5-11ea-9fd0-3b8894b7be7c.png)

While that's the real track:  
![image](https://user-images.githubusercontent.com/8313118/83938567-c8629d00-a7d5-11ea-9aa4-68ca85ec560c.png)

I guess this is due to https://github.com/pierremtb/easy-fit/issues/24. Maybe it's easy to switch to https://github.com/jimmykane/fit-parser for parsing fit files?

**Comment by erik** [comment]
Thanks for the heads up!

Looking at the changelog for that fork, doesn't seem like there are any breaking API changes, so hopefully this is a quick drop-in replacement. I'll give this a shot and see if it fixes the issue for your example file.

**Comment by erik** [comment]
Looks like that fixed it. Thanks again for reporting!
