### ISSUE TITLE
Style changes in URL?

### ISSUE THREAD

**Issue by nedbat** [erik/derive#44]
I love derive! I have just one wish: I always change the settings when I use the app (black routes, Positron).  Is there a way to change those settings from the URL, so that I could bookmark it and not have to manually adjust it each time?
Thanks <3

**Comment by erik** [comment]
Oh good idea, I like this. Another straightforward option would be to store last-used settings in local storage, but that wouldn't allow you to have multiple "presets" or bookmark your settings between machines. Maybe that's enough for the common case though?

**Comment by nedbat** [comment]
Local storage would also solve my use-case!

**Comment by erik** [comment]
@nedbat merged in a simple localStorage based implementation, let me know if you run into any issues

Thanks again for suggesting this!

**Comment by nedbat** [comment]
It works! Thanks, this makes me very happy :)
Here are 78 walks I've done with my son during lockdown:
<img width="465" alt="image" src="https://user-images.githubusercontent.com/23789/92183164-920bdc80-ee1b-11ea-92ea-9ebc6003f259.png">
I'm using dérive to identify streets we haven't walked down yet.

**Comment by hugovk** [comment]
Beautiful!
