### ISSUE TITLE
OpenStreetMap.BlackAndWhite not working

### ISSUE THREAD

**Issue by robertog09** [erik/derive#62]
Hi Erik!

First, thank you for this amazing tool. 

I have noticed that the OpenStreetMap.BlackAndWhite is currently not working.

Would it be possible to fix it?

Thanks

**Comment by erik** [comment]
Hey @robertog09, thanks for the heads up!

I found an issue on leaflet-providers (https://github.com/leaflet-extras/leaflet-providers/issues/316), which suggests that `OpenStreetMap.BlackAndWhite` is no longer available upstream, so unfortunately as far as I know the only solution is to remove it as an option. 

Maybe `CartoDB.Positron` is a suitable replacement?
