### ISSUE TITLE
How do I use this tool

### ISSUE THREAD

**Issue by paccW** [erik/derive#72]
I didnt see any instructions on how to use this. Download the source code and then what to I do with it? I dont understand how to import a gpx file to convert it to a heatmap.

**Comment by erik** [comment]
There's a hosted version on https://erik.github.io/derive. Just drag and drop files into the browser.

**Comment by paccW** [comment]
Thank you, that made things a lot easier!

**Comment by erik** [comment]
Cool, glad to hear!
